# Generated by Django 6.1 on 2026-08-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_atendimento'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servico.servico'),
        ),
    ]
